packages:
  - '.'

allowBuilds:
  bufferutil: true
  esbuild: true
  sharp: true
  unrs-resolver: true

onlyBuiltDependencies:
  - bufferutil
  - esbuild
  - sharp
  - unrs-resolver

overrides:
  'form-data@>=4.0.0 <4.0.6': '>=4.0.6'
  'postcss@<8.5.10': '>=8.5.10'
  'brace-expansion@>=5.0.0 <5.0.6': '>=5.0.6'
  'js-yaml@<3.15.0': '>=3.15.0 <4'
  'js-yaml@>=4.0.0 <=4.1.1': '>=4.1.2'
  '@babel/core@<=7.29.0': '>=7.29.1'
