import fs from "fs";
import { IMAGE_META_JSON } from "@/config/paths";
import { tryDecodeUrlComponent } from "@/utils/links/url";

export interface ImageMeta {
  width: number;
  height: number;
  blurDataURL: string;
}

// filename → meta, generated by scripts/generateImageMeta.ts from the R2
// bucket. Loaded once per server process; drafts and unknown images miss.
let manifest: Record<string, ImageMeta> | null = null;

export function getImageMeta(src: string): ImageMeta | null {
  const match = src.match(/^\/images\/([^/]+)$/);
  if (!match) return null;
  const filename = tryDecodeUrlComponent(match[1]);
  if (filename === null) return null;
  const metadata: Record<string, ImageMeta> = (manifest ??= fs.existsSync(
    IMAGE_META_JSON
  )
    ? JSON.parse(fs.readFileSync(IMAGE_META_JSON, "utf8"))
    : {});
  return Object.hasOwn(metadata, filename) ? metadata[filename] : null;
}
