import fs from "fs";
import { IMAGE_META_JSON } from "@/config/paths";

export interface ImageMeta {
  width: number;
  height: number;
  blurDataURL: string;
}

// filename → meta, generated by scripts/generateImageMeta.ts from the R2
// bucket. Loaded once per server process; drafts and unknown images miss.
let manifest: Record<string, ImageMeta> | null = null;

export function getImageMeta(src: string): ImageMeta | null {
  if (!manifest) {
    manifest = fs.existsSync(IMAGE_META_JSON)
      ? JSON.parse(fs.readFileSync(IMAGE_META_JSON, "utf8"))
      : {};
  }
  const match = src.match(/^\/images\/([^/]+)$/);
  return match ? (manifest![decodeURIComponent(match[1])] ?? null) : null;
}
